[book]
authors = ["Azimjon Ilkhomov"]
language = "en"
src = "src"
title = "cp"

[output.html]
cname = "cp.ajilk.com"
git-repository-url = "https://github.com/ajilk/cp"
additional-css = ["./theme/catppuccin.css"]
no-section-label = true
default-theme = "latte"
preferred-dark-theme = "ayu"
mathjax-support = true

[output.html.print]
enable = false
